# A scrape configuration containing exactly one endpoint to scrape from node_exporter running on a host:
scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name: 'rest_api'
      static_configs:
          - targets: ['rest-api:5001']

    - job_name: 'node_exporter'
      static_configs:
          - targets: ['node-exporter:9100']

    - job_name: 'mongo_exporter'
      static_configs:
          - targets: ['mongo-exporter:9216']

    - job_name: 'apache_exporter'
      static_configs:
          - targets: ['apache-exporter:9117']

    - job_name: 'blackbox_exporter'
      # scrape_interval: 2s
      metrics_path: /probe # The blackbox exporter's metrics endpoint.
      # scrape_timeout: 10ms
      params:
          module: [http_2xx] # Look for a HTTP 200 response.
      static_configs:
          - targets:
                - http://apache:80 # Target to probe with http on port 80.
                - http://apache:80/login.html
                - http://apache:80/players.html
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115 # The blackbox exporter's real hostname:port.

    - job_name: 'blackbox_exporter_delay'
      # scrape_interval: 2s
      metrics_path: /probe # The blackbox exporter's metrics endpoint.
      # scrape_timeout: 10ms
      params:
          module: [http_2xx] # Look for a HTTP 200 response.
      static_configs:
          - targets:
                - http://delay-web:3002
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115 # The blackbox exporter's real hostname:port.
