{
 "title": "redes-web-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_up{job=\"apache_exporter\"} == 1",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "apache_up{job=\"apache_exporter\"} == 0",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Delay probe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_exporter_delay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequential apache response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (scrape_duration_seconds{job=\"blackbox_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Status Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}