apiVersion: 1
groups:
    - orgId: 1
      name: every-minute
      folder: rules-by-severity
      interval: 1m
      rules:
          - uid: db4e683c-be81-461c-9cbc-8684e7c41beb
            title: Apache-is-down-alert-level-2
            condition: is_last_apache_up
            data:
                - refId: apache_up
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: P55236CDB9083968A
                  model:
                      editorMode: builder
                      exemplar: false
                      expr: apache_up{job="apache_exporter"}
                      hide: false
                      instant: false
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: true
                      refId: apache_up
                - refId: last_apache_up
                  relativeTimeRange:
                      from: 600
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 0
                                    - 0
                                type: gt
                            operator:
                                type: and
                            query:
                                params: []
                            reducer:
                                params: []
                                type: avg
                            type: query
                      datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                      expression: apache_up
                      intervalMs: 1000
                      maxDataPoints: 43200
                      reducer: last
                      refId: last_apache_up
                      settings:
                          mode: ''
                      type: reduce
                - refId: is_last_apache_up
                  relativeTimeRange:
                      from: 600
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 0.5
                                    - 0
                                type: lt
                            operator:
                                type: and
                            query:
                                params: []
                            reducer:
                                params: []
                                type: avg
                            type: query
                      datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                      expression: last_apache_up
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: is_last_apache_up
                      type: threshold
            dashboardUid: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
            panelId: 4
            noDataState: NoData
            execErrState: Error
            for: 3m
            annotations:
                __dashboardUid__: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
                __panelId__: '4'
                summary: Apache service is down. Level-1 couldn't fix it
            labels:
                severity: '2'
            isPaused: false
          - uid: fd365c9d-4517-4a5c-80a6-8d7e922db7ce
            title: Apache-is-down-alert-level-1
            condition: is_last_apache_up
            data:
                - refId: apache_up
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: P55236CDB9083968A
                  model:
                      editorMode: builder
                      exemplar: false
                      expr: apache_up{job="apache_exporter"}
                      hide: false
                      instant: false
                      intervalMs: 1000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: true
                      refId: apache_up
                - refId: last_apache_up
                  relativeTimeRange:
                      from: 600
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 0
                                    - 0
                                type: gt
                            operator:
                                type: and
                            query:
                                params: []
                            reducer:
                                params: []
                                type: avg
                            type: query
                      datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                      expression: apache_up
                      intervalMs: 1000
                      maxDataPoints: 43200
                      reducer: last
                      refId: last_apache_up
                      settings:
                          mode: ''
                      type: reduce
                - refId: is_last_apache_up
                  relativeTimeRange:
                      from: 600
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 0.5
                                    - 0
                                type: lt
                            operator:
                                type: and
                            query:
                                params: []
                            reducer:
                                params: []
                                type: avg
                            type: query
                      datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                      expression: last_apache_up
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: is_last_apache_up
                      type: threshold
            dashboardUid: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
            panelId: 4
            noDataState: NoData
            execErrState: Error
            for: 2m
            annotations:
                __dashboardUid__: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
                __panelId__: '4'
                summary: Apache service is down
            labels:
                severity: '1'
            isPaused: false
          - uid: afdcce5d-c64a-40f2-93b4-a0beab38fc30
            title: Apache slow
            condition: C
            data:
                - refId: A
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: P55236CDB9083968A
                  model:
                      datasource:
                          type: prometheus
                          uid: P55236CDB9083968A
                      editorMode: builder
                      expr: sum by(job) (scrape_duration_seconds{job="blackbox_exporter"})
                      interval: ''
                      intervalMs: 15000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: true
                      refId: A
                - refId: B
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params: []
                                type: gt
                            operator:
                                type: and
                            query:
                                params:
                                    - B
                            reducer:
                                params: []
                                type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      hide: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      reducer: last
                      refId: B
                      type: reduce
                - refId: C
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 1
                                type: gt
                            operator:
                                type: and
                            query:
                                params:
                                    - C
                            reducer:
                                params: []
                                type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: B
                      hide: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
            dashboardUid: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
            panelId: 1
            noDataState: NoData
            execErrState: Error
            for: 2m
            annotations:
                __alertId__: '1'
                __dashboardUid__: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
                __panelId__: '1'
                description: Apache sequence is running slow
            labels:
                severity: '1'
            isPaused: false
          - uid: b34e0ae7-52eb-4b48-a0ee-5f2167f865f2
            title: Delay probe alert
            condition: C
            data:
                - refId: A
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: P55236CDB9083968A
                  model:
                      datasource:
                          type: prometheus
                          uid: P55236CDB9083968A
                      editorMode: builder
                      expr: probe_duration_seconds{job="blackbox_exporter_delay"}
                      interval: ''
                      intervalMs: 15000
                      legendFormat: __auto
                      maxDataPoints: 43200
                      range: true
                      refId: A
                - refId: B
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params: []
                                type: gt
                            operator:
                                type: and
                            query:
                                params:
                                    - B
                            reducer:
                                params: []
                                type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: A
                      hide: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      reducer: last
                      refId: B
                      type: reduce
                - refId: C
                  datasourceUid: __expr__
                  model:
                      conditions:
                          - evaluator:
                                params:
                                    - 4
                                type: gt
                            operator:
                                type: and
                            query:
                                params:
                                    - C
                            reducer:
                                params: []
                                type: last
                            type: query
                      datasource:
                          type: __expr__
                          uid: __expr__
                      expression: B
                      hide: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: C
                      type: threshold
            dashboardUid: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
            panelId: 3
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
                __dashboardUid__: bc8416ec-b52d-4942-8e1a-931f0f39ebf2
                __panelId__: '3'
            labels:
                severity: '1'
            isPaused: false
